name = "tg-massage"
main = "index.js"
compatibility_date = "2025-04-01"

# Привязка KV (обязательно)
kv_namespaces = [
  { binding = "myVar", id = "01f999166da04c68a9a10b4e33cc132d" }
]

# Cron-триггер — каждый час
[[triggers]]
crons = ["0 * * * *"]
