name = "tg-massage"
main = "tg-massage.worker.js"
compatibility_date = "2025-04-01"

# Настройки для обычного Worker
workers = true

# Переменные окружения (секреты)
[vars]
# Здесь можно оставить пусто, мы будем использовать secrets

# Cron триггер
[[triggers]]
crons = ["0 * * * *"]   # каждый час
